### PR TITLE
sha256: fix pre-processor #if

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
I'm glad that we caught this before a release!

**Comment by cperciva** [comment]
Not sure I see the issue here.  The C standard says that undefined identifiers in an `#if` preprocessor directive get converted to `0`.

**Comment by gperciva** [comment]
Sure, it's the best type of correct.  But it pops up with a compiler warning, which of course we can disable or ignore... but given that all the other cases use `#ifdef CPUSUPPORT_`, why not do the same here, and avoid the warnings?

**Comment by cperciva** [comment]
Oh, I see.  Silly compilers...

**Pull request merged**
