### PR TITLE
events.c: limit # of events processed at once

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
This is a slightly modified version of commit b68021c1f9d497524c68fc6bdc5a042639e00698 from the tarsnap server source, although I ran into it with the kivaloo bench programs.

**Comment by gperciva** [comment]
At the time, you noted it as being a "dirty hack".  I'm not clear on how this could be cleaner, but hopefully this will jog your memory.

**Comment by cperciva** [comment]
The "right" solution for this is to use the `events_interrupt` API you added a while back.  I used this hack in the tarsnap server code because I didn't have `events_interrupt` and I needed to make sure I could handle a signal before too much time had passed.

**Comment by gperciva** [comment]
hmm, ok.

**Pull request closed without merging**
