### PR TITLE
Switch to PARSENUM_EX

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
Tentative plan for implementing `PARSENUM` with `PARSENUM_EX`.  PR #192 is the first step in this process; I'm including the entire (draft) thing so you can see where I'm aiming.

**Comment by gperciva** [comment]
Updated the whole "switch to `PARSENUM_EX`" PR, but #195 is still the next step in the process, before this one should have serious consideration.

**Comment by cperciva** [comment]
Was there anything else we wanted in PARSENUM_EX?  I vaguely remember you mentioning something else in addition to the base.

**Comment by gperciva** [comment]
Yes, the ability to ignore "trailing characters" as EINVAL.  I have that as a separate branch.

**Comment by gperciva** [comment]
Added as a currently-draft PR #199.  I'll make that a real PR once this is merged.

**Pull request merged**
