### PR TITLE
Improve events testing

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by cperciva** [comment]
LGTM, but as I was looking at this I wondered why `test_interrupt_run` has `while ((ret = events_run()) { ...`.

The function `events_run` is not required to handle events forever -- in fact at one point I had an implementation which would return after a hard-coded number of events were processed -- and will return `0` if nothing breaks.

This should probably be looping while `events_run` returns `0`, with a `if (done) break;` to escape the loop at the appropriate time.

I'll leave this PR unmerged for now in case you want to add another commit to it...

**Comment by gperciva** [comment]
Right, at first I thought that adding an `events_run_done` would jeopardize actually testing `events_interrupt`, but when I deliberately break that function I see that the test breaks appopriately.

**Comment by gperciva** [comment]
... shall I go ahead and rebase this?

**Comment by cperciva** [comment]
Still not right.  `events_run` can return zero whenever it wants.  I think the code needs to look like

```
while ((ret = events_run()) == 0) {
    if (events_run_done)
        break;
}
if (ret) {
    /* handle error case here */
}
```

**Comment by gperciva** [comment]
Judging from how `events_run()` is used in kivaloo, I think it's more idiomatic to wrap it in a `do ... while` and have the error-handing inside the loop.

**Comment by cperciva** [comment]
Ok, we could do it that way.  But anything nonzero from `events_run` is an error, not just `-1`.  (The events code itself will return `-1` if it has an internal error, but we don't specify what error codes callbacks might return.)

**Comment by cperciva** [comment]
LGTM

**Comment by gperciva** [comment]
Rebased, ready for merge.

**Pull request merged**
