### PR TITLE
Style: fix whitespace

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
This replaces #521.

I think it's been 6-12 months since I last tried to get 3rd-party PRs to allow us to "approve" the github action run, so it's time to try again.

**Comment by cperciva** [comment]
Needs a "reported by" tag in the commit message.  (Ok @TimWolla only reported one of the three, but it's a matter of principle.)

**Comment by gperciva** [comment]
Done.

**Comment by cperciva** [comment]
@TimWolla Should this be `Reported by: Tim Wolla` or `Reported by: Tim Düsterhus`?

**Comment by gperciva** [comment]
We already have Tim D in the repo as the author of 28dfe297b66e25fd708031613590f5291cb06e9d, so it makes sense to use that name for the "Reported by".

Commit message amended.

**Comment by TimWolla** [comment]
> Should this be `Reported by: Tim Wolla` or `Reported by: Tim Düsterhus`?

As Graham correctly determined, “Tim Düsterhus”.

**Comment by TimWolla** [comment]
> I think it's been 6-12 months since I last tried to get 3rd-party PRs to allow us to "approve" the github action run, so it's time to try again.

You would need the [`pull_request` workflow trigger](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request) in the workflow definition for it to run on pull requests from forks.

**Pull request merged**
