### PR TITLE
crypto_aes.c: typo in openssl_oneshot()

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
This is such an embarrassing mistake that I'm sorely tempted to rebase it into the previous commit and do a force push to replace master.  (i.e. totally rewriting history from ~6 hours ago)

I'm also really curious about how it worked -- the tests pass, even when run within valgrind.  I guess that the openssl AES_KEY structure happens to store the key first in memory?

**Comment by gperciva** [comment]
Another option would be to switch that function to be:
```
{
        struct AES_KEY kexp;

        /* Expand the key, encrypt, and clean up. */
        AES_set_encrypt_key(key, (int)(len * 8), &kexp);
        AES_encrypt(ptext, ctext, &kexp);
        insecure_memzero(&kexp, sizeof(AES_KEY));

        return (0);
}
```

**Comment by gperciva** [comment]
Ignore that last comment; I must have been confused about which terminal window I was in, when I ran `make test`.

**Comment by cperciva** [comment]
Yeah, let's change it to use `struct AES_KEY` rather than `void *`.

**Comment by gperciva** [comment]
I tentatively think this works.

**Pull request merged**
